### ISSUE TITLE
Genotype file problem

### ISSUE THREAD

**Issue by feasiblee** [reworkhow/JWAS.jl#154]
Hello, what should I do if the genotype file has NA values ​​and then read it?

**Comment by zhaotianjing** [comment]
Hi, in `get_genotypes()` function, there is an argument of `missing_value`, and by default, it is `missing_value=9.0`. I suggest you replace the NA with a 9.0 before your analysis.

**Comment by feasiblee** [comment]
Problem solved, thank you

**Comment by feasiblee** [comment]
Hello, I am doing out=runMCMC(model,phenotypes), and ERROR appears: Some levels in CW:id for individuals of interest are not found in training individuals (IDs with non-missing records).You may delete those rows or replace those values ​​with missing. For this question, my phenotypic data reading is like this: phenotypes = CSV.read(phenofile,DataFrame,delim = ',',header=true,missingstring=["NA"]).
