### ISSUE TITLE
Error running SSBR

### ISSUE THREAD

**Issue by balathumma10** [reworkhow/JWAS.jl#21]
Hi, I get the following error trying to run SSBR using the test data. Could you please help.
julia> out1=runMCMC(model,phenotypes,methods="BayesC",single_step_analysis=true,pedigree=pedigree,chain_length=5000,output_samples_frequency=100);
ERROR: MethodError: no method matching runMCMC(::JWAS.MME, ::DataFrames.DataFrame; methods="BayesC", single_step_analysis=true, pedigree=JWAS.PedModule.Pedigree(301, Dict{AbstractString,JWAS.PedModule.PedNode}(Pair{AbstractString,JWAS.PedModule.PedNode}("1", JWAS.PedModule.PedNode(1, "0", "0", 0.0)),Pair{AbstractString,JWAS.PedModule.PedNode}("54", JWAS.PedModule.PedNode(2, "0", "0", 0.0)),Pair{AbstractString,JWAS.PedModule.PedNode}("101", JWAS.PedModule.PedNode(5, "42", "76", 0.0)),Pair{AbstractString,JWAS.PedModule.PedNode}("41", JWAS.PedModule.PedNode(6, "0", "0", 0.0)),Pair{AbstractString,JWAS.PedModule.PedNode}("65", JWAS.PedModule.PedNode(7, "0", "0", 0.0)),Pair{AbstractString,JWAS.PedModule.PedNode}("299", JWAS.PedModule.PedNode(12, "141", "171", 0.125)),Pair{AbstractString,JWAS.PedModule.PedNode}("168", JWAS.PedModule.PedNode(15, "16", "72", 0.0)),Pair{AbstractString,JWAS.PedModule.PedNode}("159", JWAS.PedModule.PedNode(18, "3", "64", 0.0)),Pair{AbstractString,JWAS.PedModule.PedNode}("228", JWAS.PedModule.PedNode(25, "127", "155", 0.0)),Pair{AbstractString,JWAS.PedModule.PedNode}("190", JWAS.PedModule.PedNode(28, "21", "60", 0.0))…), Dict(7802=>0.0,9905=>0.0,158=>0.0,9122=>0.0,2780=>0.0,4286=>0.0,249=>0.0,384=>0.0,173=>0.0,20597=>0.0…), Set{Any}(), Set{Any}(), Set{Any}(), Set{Any}()), chain_length=5000, output_samples_frequency=100)
Closest candidates are:
  runMCMC(::Any, ::Any; Pi, burnin, chain_length, starting_value, missing_phenotypes, constraint, estimatePi, methods, output_file, printout_frequency, printout_MCMCinfo, output_samples_frequency, update_priors_frequency) at C:\Users\balat\.julia\v0.6\JWAS\src\1.JWAS/src\MCMC/MCMC.jl:42 got unsupported keyword arguments "single_step_analysis", "pedigree"

**Comment by reworkhow** [comment]
Can you try Pkg.checkout("JWAS") to get the latest unofficial version?

**Comment by reworkhow** [comment]
You have gotten the newest unofficial version. You can run Pkg.status("JWAS") to see the version.  restart kernel and run your analysis again to see.

**Comment by balathumma10** [comment]
Thank you very much. It appears to be working now. I think the problem was
with using JWAS commands.

**Comment by balathumma10** [comment]
Could you please let me know how to get the hybrid matrix and the marker
effects fro the output file.
Thank you.

**Comment by reworkhow** [comment]
The posterior mean for marker effects can be obtained as 
```
out["Posterior mean of marker effects"]
```
The samples for marker effects should be saved into a text file if option `output_samples_frequency` is on. 

Do you mean the left-hand side of the mixed-model equation?

**Comment by reworkhow** [comment]
There are two interfaces. Are you using runSSBR or runMCMC? I saw you have used both.

**Comment by balathumma10** [comment]
Yes, I tried to run both the interfaces. When I tried to run runMCMC with
the following it did not work. runSSBR worked but without the
output_samples_frequency option.

out1=runMCMC(model1,phenotypes,methods="RR-BLUP",single_step_analysis=true,pedigree=pedigree,chain_length=5000,output_samples_frequency=100);

**Comment by reworkhow** [comment]
If you are running runSSBR(), you can get the posterior mean of the marker effects as
`out.posMeans.meanMarkerEffects`

We are going to deprecate runSSBR() and run all analysis using runMCMC(). Can you let me know the 
error you got in runMCMC?
