### ISSUE TITLE
genotype file , phenotype file checking

### ISSUE THREAD

**Issue by reworkhow** [reworkhow/JWAS.jl#5]

**Comment by nlopezvillalobos** [comment]
I am trying to repeat the the JWAS example but I got the following error message when running
using DataFrames,JWAS,JWAS.Datasets
INFO: Precompiling module JWAS...
ERROR: LoadError: LoadError: ArgumentError: ProgressMeter not found in path
 in compilecache at loading.jl:376
 in require at loading.jl:224
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at client.jl:284
 in _start at client.jl:411
while loading C:\Users\nlopez\.julia\v0.4\JWAS\src\2.PedModule/src/PedModule.jl, in expression starting on line 4
while loading C:\Users\nlopez\.julia\v0.4\JWAS\src\JWAS.jl, in expression starting on line 7

**Comment by reworkhow** [comment]
Can you try to upgrade Julia to 0.5 to see? Some functions only work with 0.5 now in order to take advantage of features from Julia 0.5. Please comment if you have any question, for example, speed or suggested new features...

**Comment by nlopezvillalobos** [comment]
Hi Hao,
Thank you for your help, I made some progress after updating Julia with version 0.5
I went to the basic example

I. Univariate Linear Additive Genetic Model

But got more problems

I run ok
using DataFrames,JWAS,JWAS.Datasets
pedfile   = Datasets.dataset("testMME","pedigree.txt")
phenofile = Datasets.dataset("testMME","simple.txt");

but running
;cat $pedfile

Produce the following error message
LoadError: could not spawn `cat 'C:\Users\nlopez\.julia\v0.5\JWAS\src\5.Datasets/src\..\data\testMME\pedigree.txt'`: no such file or directory (ENOENT)
while loading In[4], in expression starting on line 1

in _jl_spawn(::String, ::Array{String,1}, ::Ptr{Void}, ::Base.Process, ::RawFD, ::RawFD, ::RawFD) at .\process.jl:321
in #414 at .\process.jl:478 [inlined]
in setup_stdio(::Base.##414#415{Cmd,Ptr{Void},Base.Process}, ::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:466
in #spawn#413(::Nullable{Base.ProcessChain}, ::Function, ::Cmd, ::Tuple{RawFD,RawFD,RawFD}, ::Bool, ::Bool) at .\process.jl:477
in run(::Cmd) at .\process.jl:591
in repl_cmd(::Cmd, ::Base.PipeEndpoint) at .\client.jl:91

The following command
d1 = readtable(phenofile)
works ok

But the next command
ped = get_pedigree(pedfile);

produce the following error,

LoadError: UndefVarError: get_pedigree not defined

while loading In[6], in expression starting on line 1



Also it is seems that the function build_model  does not work when running the rest of the code

varRes=1.0

model1 = build_model("y = intercept + Age + Animal",varRes)

set_covariate(model1,"Age")

G=2.5

set_random(model1,"Animal",ped,G)

LoadError: UndefVarError: build_model not defined
while loading In[7], in expression starting on line 2





Thank you for your help,
Kind regards,
Nicolas

**Comment by reworkhow** [comment]
Thanks. The reason why  `;cat $pedfile` is not working is in Julia starting with a semicolon ; will run the bash command line directly, there is a `cat` command in Mac to show the content of the file. However, I guess you're using a Windows machine where `cat` is not available.

Can you try to run Pkg.checkout("JWAS") and then run the example. Pkg.checkout("JWAS") will provide the newest unregistered JWAS.  I just tested it and made sure it works. 

It is a little confusing since Julia just upgraded to 0.5 and some old features are replaced by new features, and I'm still working on updating the JWAS package. I should finish all updates this week and will inform you once I finish. Now it should work without errors but probably some warnings.

**Comment by nlopezvillalobos** [comment]
Thank you for your help,  I completed the example successfully.
