### ISSUE TITLE
Rounding error in "P+S" for InverseWishart()

### ISSUE THREAD

**Issue by cbkmephisto** [reworkhow/JWAS.jl#7]
<pre>ERROR: LoadError: ArgumentError: matrix is not symmetric/Hermitian. This error can be avoided by calling cholfact(Hermitian(A)) which will ignore either the upper or lower triangle of the matrix.
 in cholfact(::Array{Float64,2}, ::Symbol) at ./linalg/cholesky.jl:281
 in macro expansion at /home/hailins/.julia/v0.5/JWAS/src/1.JWAS/src/MCMC/MT_MCMC_BayesC.jl:283 [inlined]
 in macro expansion at /home/hailins/.julia/v0.5/ProgressMeter/src/ProgressMeter.jl:473 [inlined]
 in #MT_MCMC_BayesC#23(::Float64, ::Array{Float64,2}, ::Int64, ::Bool, ::Bool, ::Bool, ::String, ::Int64, ::Int64, ::JWAS.#MT_MCMC_BayesC, ::Int64, ::JWAS.MME, ::DataFrames.DataFrame) at /home/hailins/.julia/v0.5/JWAS/src/1.JWAS/src/MCMC/MT_MCMC_BayesC.jl:161
 in (::JWAS.#kw##MT_MCMC_BayesC)(::Array{Any,1}, ::JWAS.#MT_MCMC_BayesC, ::Int64, ::JWAS.MME, ::DataFrames.DataFrame) at ./<missing>:0
 in #runMCMC#26(::Float64, ::Int64, ::Array{Float64,2}, ::Bool, ::Bool, ::Bool, ::String, ::Int64, ::Int64, ::Int64, ::JWAS.#runMCMC, ::JWAS.MME, ::DataFrames.DataFrame) at /home/hailins/.julia/v0.5/JWAS/src/1.JWAS/src/MCMC/MCMC.jl:74
 in (::JWAS.#kw##runMCMC)(::Array{Any,1}, ::JWAS.#runMCMC, ::JWAS.MME, ::DataFrames.DataFrame) at ./<missing>:0
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /work/hailins/20160816-JWAS-AHA-BWCE-MAT-ref/8.reByCECG.123only.aod/zzz-2-runMCMC.jl, in expression starting on line 184</pre>

in ~/.julia/v0.5/JWAS/src/1.JWAS/src/MCMC/MT_MCMC_BayesC.jl line ~ 275:
<pre>G0 = rand(InverseWishart(νG0 + q, P+S))</pre>
It is suggested to change to
<pre>G0 = rand(InverseWishart(νG0 + q, round(P+S, 7)))</pre>

**Comment by cbkmephisto** [comment]
Still, rounding may not be able to solve the problem, unless it's rounded to 2 or 1 decimal(s). I tried flipping the lower triangle before calculating R0 and G0, and so far so good.

In ~/.julia/v0.5/JWAS/src/1.JWAS/src/MCMC/MT_MCMC_BayesC.jl

```julia
        # ~ line 214
        PSr = round(PRes+SRes, 6)
        LT=LowerTriangular(PSr)
        PSr=LT + LT' - diagm(diag(PSr))
        writedlm("PSr", PSr)  # to see the problem

        R0 = rand(InverseWishart(νR0 + nObs, PSr))
```
```julia
            # ~ line 270
            PSg = round(P+S, 6)
            LT=LowerTriangular(PSg)
            PSg=LT + LT' - diagm(diag(PSg))
            writedlm("PSg", PSg)  # to see the problem

            G0 = rand(InverseWishart(νG0 + q, PSg))
```

**Comment by reworkhow** [comment]
use Symmetric() function
