### ISSUE TITLE
MCMC_samples_marker_effects_variances_geno.txt is empty

### ISSUE THREAD

**Issue by animBreedTools** [reworkhow/JWAS.jl#72]
Running a multi-trait SSBR. The example on the webpage does produce MCMC_samples_marker_effects_variances_geno.txt, but it is empty.

**Comment by reworkhow** [comment]
I just added this feature to allow JWAS to save samples for marker effect variances in multi-trait analysis. You can update JWAS to the latest unofficial version to use it now. I will make it official in the next release.

Each sample is saved in k rows (k=number of traits).
